----------------------------------------------------------------------------------
-- Company      :
-- Engineer     : Shekhar Mishra
--
-- Create Date  : 05.07.2026
-- Module Name  : n_bit_johnson_counter
-- Project Name : FPGA Design Library
-- Target Device: Generic FPGA
--
-- Description:
--   Parameterizable N-bit Johnson Counter (Twisted Ring Counter).
--
--   A Johnson counter is implemented by feeding the inverted output of
--   the last stage back to the first stage while shifting the remaining
--   register contents.
--
--   Unlike a conventional ring counter, an N-bit Johnson counter
--   generates 2 × N unique states before repeating.
--
--   Example (4-bit):
--
--       0000
--         │
--         ▼
--       1000
--         ▼
--       1100
--         ▼
--       1110
--         ▼
--       1111
--         ▼
--       0111
--         ▼
--       0011
--         ▼
--       0001
--         ▼
--       0000
--
-- Features:
--   • Parameterizable counter width
--   • Generates 2 × N unique states
--   • Synchronous active-high reset
--   • Clock enable support
--   • Fully synthesizable
--   • FPGA-friendly RTL implementation
--
-- Applications:
--   • Sequence generators
--   • Timing generators
--   • Non-overlapping control signals
--   • Digital pattern generation
--   • Simple state machines
--
----------------------------------------------------------------------------------

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity n_bit_johnson_counter is

    generic(

        ----------------------------------------------------------------------
        -- Number of stages in the Johnson counter.
        ----------------------------------------------------------------------
        COUNT_WIDTH : natural := 4

    );

    port(

        ----------------------------------------------------------------------
        -- System Interface
        ----------------------------------------------------------------------
        clk : in std_logic;      -- System clock
        rst : in std_logic;      -- Active-high synchronous reset
        en  : in std_logic;      -- Clock enable

        ----------------------------------------------------------------------
        -- Counter Output
        ----------------------------------------------------------------------
        count_out : out std_logic_vector(COUNT_WIDTH-1 downto 0)

    );

end n_bit_johnson_counter;

architecture rtl of n_bit_johnson_counter is

    --------------------------------------------------------------------------
    -- Current Johnson counter state.
    --------------------------------------------------------------------------
    signal johnson_reg : std_logic_vector(COUNT_WIDTH-1 downto 0);

    --------------------------------------------------------------------------
    -- Next-state value of the Johnson counter.
    --------------------------------------------------------------------------
    signal johnson_next : std_logic_vector(COUNT_WIDTH-1 downto 0);

begin

    --------------------------------------------------------------------------
    -- Next-State Logic
    --
    -- Shift the register one position to the right while feeding the
    -- inverted least significant bit (LSB) back into the most significant
    -- bit (MSB).
    --
    -- Example (4-bit):
    --
    -- Current      Next
    -- ---------------------
    -- 0000   -->   1000
    -- 1000   -->   1100
    -- 1100   -->   1110
    -- 1110   -->   1111
    -- 1111   -->   0111
    -- 0111   -->   0011
    -- 0011   -->   0001
    -- 0001   -->   0000
    --------------------------------------------------------------------------
    johnson_next <= (not johnson_reg(0)) &
                    johnson_reg(COUNT_WIDTH-1 downto 1);

    --------------------------------------------------------------------------
    -- Counter Output
    --------------------------------------------------------------------------
    count_out <= johnson_reg;

    --------------------------------------------------------------------------
    -- Johnson Counter Register
    --
    -- Reset:
    --   Initializes the counter to the all-zero state, which is a valid
    --   starting state for a Johnson counter.
    --
    -- Enable:
    --   Advances the Johnson sequence only when EN is asserted.
    --
    -- Operation:
    --   Loads the next state generated by the combinational next-state
    --   logic on every rising edge of the clock.
    --------------------------------------------------------------------------
    johnson_counter_pr : process(clk)
    begin

        if rising_edge(clk) then

            --------------------------------------------------------------
            -- Synchronous Reset
            --------------------------------------------------------------
            if rst = '1' then

                johnson_reg <= (others => '0');

            --------------------------------------------------------------
            -- Normal Counter Operation
            --------------------------------------------------------------
            elsif en = '1' then

                johnson_reg <= johnson_next;

            end if;

        end if;

    end process johnson_counter_pr;

end rtl;