----------------------------------------------------------------------------------
-- Company      :
-- Engineer     : Shekhar Mishra
--
-- Create Date  : 30.06.2026
-- Module Name  : universal_shift_reg
-- Project Name : FPGA Design Library
-- Target Device: Generic FPGA
--
-- Description:
--   Parameterizable Universal Shift Register.
--
--   This module implements a configurable N-bit universal shift register
--   capable of performing hold, shift-left, shift-right and parallel
--   load operations.
--
--   During shift operations, the serial input is taken from the
--   corresponding bit of the input vector 'd':
--
--      Shift Left  : d(0) is shifted into the LSB.
--      Shift Right : d(WIDTH-1) is shifted into the MSB.
--
-- Features:
--   • Generic register width
--   • Hold operation
--   • Shift left
--   • Shift right
--   • Parallel load
--   • Clock enable
--   • Synchronous active-high reset
--   • Fully synthesizable
--
-- Control Encoding:
--
--   "00" -> Hold current value
--   "01" -> Shift Left
--   "10" -> Shift Right
--   "11" -> Parallel Load
--
-- Applications:
--   • Serial-to-Parallel conversion
--   • Parallel-to-Serial conversion
--   • Delay pipelines
--   • Data buffering
--   • Communication interfaces
--
----------------------------------------------------------------------------------

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity universal_shift_reg is

    generic(

        ----------------------------------------------------------------------
        -- Width of the shift register.
        ----------------------------------------------------------------------
        WIDTH : natural := 4

    );

    port(

        ----------------------------------------------------------------------
        -- System Interface
        ----------------------------------------------------------------------
        clk  : in std_logic;      -- System clock
        rst  : in std_logic;      -- Active-high synchronous reset
        en   : in std_logic;      -- Clock enable

        ----------------------------------------------------------------------
        -- Control Input
        --
        -- 00 : Hold
        -- 01 : Shift Left
        -- 10 : Shift Right
        -- 11 : Parallel Load
        ----------------------------------------------------------------------
        ctrl : in std_logic_vector(1 downto 0);

        ----------------------------------------------------------------------
        -- Data Input
        --
        -- Parallel Load:
        --      Entire vector is loaded.
        --
        -- Shift Left:
        --      d(0) is used as serial input.
        --
        -- Shift Right:
        --      d(WIDTH-1) is used as serial input.
        ----------------------------------------------------------------------
        d : in std_logic_vector(WIDTH-1 downto 0);

        ----------------------------------------------------------------------
        -- Register Output
        ----------------------------------------------------------------------
        q : out std_logic_vector(WIDTH-1 downto 0)

    );

end universal_shift_reg;

architecture rtl of universal_shift_reg is

    --------------------------------------------------------------------------
    -- Current register value.
    --------------------------------------------------------------------------
    signal r_reg : std_logic_vector(WIDTH-1 downto 0);

    --------------------------------------------------------------------------
    -- Next-state value.
    --------------------------------------------------------------------------
    signal r_next : std_logic_vector(WIDTH-1 downto 0);

begin

    --------------------------------------------------------------------------
    -- Next-State Logic
    --------------------------------------------------------------------------
    with ctrl select

        r_next <=

            r_reg                               when "00", -- Hold

            r_reg(WIDTH-2 downto 0) & d(0)      when "01", -- Shift Left

            d(WIDTH-1) &
            r_reg(WIDTH-1 downto 1)             when "10", -- Shift Right

            d                                   when "11", -- Parallel Load
            
            (others => 'X')                     when others;

    --------------------------------------------------------------------------
    -- Register Output
    --------------------------------------------------------------------------
    q <= r_reg;

    --------------------------------------------------------------------------
    -- Shift Register
    --
    -- Reset:
    --      Clears the register.
    --
    -- Enable:
    --      Updates the register only when EN is asserted.
    --
    -- Operation:
    --      Loads the next-state value generated by the combinational
    --      control logic.
    --------------------------------------------------------------------------
    shift_register_pr : process(clk)
    begin

        if rising_edge(clk) then

            if rst = '1' then

                r_reg <= (others => '0');

            elsif en = '1' then

                r_reg <= r_next;

            end if;

        end if;

    end process shift_register_pr;

end rtl;