----------------------------------------------------------------------------------
-- Company      :
-- Engineer     : Shekhar Mishra
--
-- Create Date  : 01.07.2026
-- Module Name  : n_bit_binary_counter
-- Project Name : FPGA Design Library
-- Target Device: Generic FPGA
--
-- Description:
--   Parameterizable N-bit binary counter.
--
--   This module implements a generic binary counter supporting
--   synchronous clear, parallel load, up count and down count
--   operations. The required operation is selected using a
--   two-bit control input.
--
-- Features:
--   - Generic counter width
--   - Synchronous active-high reset
--   - Clock enable
--   - Synchronous clear
--   - Parallel load
--   - Up counter
--   - Down counter
--   - Fully synthesizable
--
-- Control Encoding:
--
--   ctrl = "00"  -> Clear counter
--   ctrl = "01"  -> Load input 'd'
--   ctrl = "10"  -> Increment counter
--   ctrl = "11"  -> Decrement counter
--
-- Applications:
--   - Address generators
--   - Event counters
--   - Timers
--   - Frequency dividers
--   - General-purpose digital systems
--
----------------------------------------------------------------------------------

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity n_bit_binary_counter is

    generic(

        ----------------------------------------------------------------------
        -- Width of the binary counter.
        ----------------------------------------------------------------------
        COUNTER_WIDTH : natural := 4

    );

    port(

        ----------------------------------------------------------------------
        -- System Interface
        ----------------------------------------------------------------------
        clk  : in std_logic;      -- System clock
        rst  : in std_logic;      -- Active-high synchronous reset
        en   : in std_logic;      -- Clock enable

        ----------------------------------------------------------------------
        -- Counter Control
        ----------------------------------------------------------------------
        ctrl : in std_logic_vector(1 downto 0);

        ----------------------------------------------------------------------
        -- Parallel load value.
        ----------------------------------------------------------------------
        d    : in std_logic_vector(COUNTER_WIDTH-1 downto 0);

        ----------------------------------------------------------------------
        -- Counter output.
        ----------------------------------------------------------------------
        q    : out std_logic_vector(COUNTER_WIDTH-1 downto 0)

    );

end n_bit_binary_counter;

architecture rtl of n_bit_binary_counter is

    --------------------------------------------------------------------------
    -- Current counter value.
    --------------------------------------------------------------------------
    signal r_reg : unsigned(COUNTER_WIDTH-1 downto 0);

    --------------------------------------------------------------------------
    -- Next-state value of the counter.
    --------------------------------------------------------------------------
    signal r_next : unsigned(COUNTER_WIDTH-1 downto 0);

begin

    --------------------------------------------------------------------------
    -- Counter Output
    --------------------------------------------------------------------------
    q <= std_logic_vector(r_reg);

    --------------------------------------------------------------------------
    -- Next-State Logic
    --
    -- Selects the next counter value based on the control input.
    --
    -- 00 : Clear counter
    -- 01 : Load external data
    -- 10 : Increment counter
    -- 11 : Decrement counter
    --------------------------------------------------------------------------
    with ctrl select

        r_next <=

            (others => '0') when "00",      -- Clear

            unsigned(d)     when "01",      -- Parallel Load

            r_reg + 1       when "10",      -- Count Up

            r_reg - 1       when "11",      -- Count Down

            (others => 'X') when others;    -- Invalid control (simulation only)

    --------------------------------------------------------------------------
    -- Counter Register
    --
    -- Operation:
    --
    -- Reset:
    --      Clears the counter to zero.
    --
    -- Enable:
    --      Updates the counter only when EN is asserted.
    --
    -- Next-State:
    --      Loads the value generated by the combinational next-state logic.
    --------------------------------------------------------------------------
    counter_pr : process(clk)
    begin

        if rising_edge(clk) then

            if rst = '1' then

                r_reg <= (others => '0');

            elsif en = '1' then

                r_reg <= r_next;

            end if;

        end if;

    end process counter_pr;

end rtl;