----------------------------------------------------------------------------------
-- Company: 
-- Engineer: 
-- 
-- Create Date: 08.07.2026 21:12:54
-- Design Name: 
-- Module Name: basic_package - Behavioral
-- Project Name: 
-- Target Devices: 
-- Tool Versions: 
-- Description: 
-- 
-- Dependencies: 
-- 
-- Revision:
-- Revision 0.01 - File Created
-- Additional Comments:
-- 
----------------------------------------------------------------------------------


library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

-- Uncomment the following library declaration if using
-- arithmetic functions with Signed or Unsigned values
--use IEEE.NUMERIC_STD.ALL;

-- Uncomment the following library declaration if instantiating
-- any Xilinx leaf cells in this code.
--library UNISIM;
--use UNISIM.VComponents.all;
package basic_package is


function clog2( n : natural) return natural;
function gray_to_binary ( gray : std_logic_vector
)
return std_logic_vector;
function binary_to_gray ( binary : std_logic_vector
)
return std_logic_vector;

end basic_package;
package body basic_package is
 function clog2( n : natural) return natural is
  begin
     if n <= 1 then
         return 1;
     end if;
     for i in 0 to 30 loop
         if (2 ** i >= n) then
             return i;
         end if;
     end loop;
      return 31; 
 end function clog2;
 
 ------------------------------------------------------------------------------
-- Function : gray_to_binary
--
-- Description:
--   Converts a Gray-coded vector into its binary equivalent.
--
-- Parameters:
--   gray : Input Gray-coded vector.
--
-- Returns:
--   Binary representation of the input Gray code.
--
-- Notes:
--   • Generic width (works for any vector length).
--   • Synthesizable.
--   • Intended for asynchronous FIFO pointer synchronization.
------------------------------------------------------------------------------
function gray_to_binary
(
    gray : std_logic_vector
)
return std_logic_vector is

    variable binary : std_logic_vector(gray'range);

begin

    --------------------------------------------------------------------------
    -- MSB remains unchanged.
    --------------------------------------------------------------------------
    binary(binary'left) := gray(gray'left);

    --------------------------------------------------------------------------
    -- Remaining bits are obtained by cumulative XOR.
    --------------------------------------------------------------------------
    for i in binary'left-1 downto binary'right loop

        binary(i) := binary(i+1) xor gray(i);

    end loop;

    return binary;

end function;

------------------------------------------------------------------------------
-- Function : binary_to_gray
--
-- Description:
--   Converts a binary value into its Gray-code equivalent.
--
-- Parameters:
--   binary : Binary input vector.
--
-- Returns:
--   Gray-coded representation of the binary input.
--
-- Notes:
--   • Generic width (works for any vector length).
--   • Synthesizable.
--   • Intended for asynchronous FIFO pointer generation.
------------------------------------------------------------------------------
function binary_to_gray
(
    binary : std_logic_vector
)
return std_logic_vector is

    variable gray : std_logic_vector(binary'range);

begin

    --------------------------------------------------------------------------
    -- MSB remains unchanged.
    --------------------------------------------------------------------------
    gray(gray'left) := binary(binary'left);

    --------------------------------------------------------------------------
    -- Remaining bits are generated by XORing adjacent binary bits.
    --------------------------------------------------------------------------
    for i in gray'left-1 downto gray'right loop

        gray(i) := binary(i+1) xor binary(i);

    end loop;

    return gray;

end function;
end package body;